# Generated by Django 4.2.28 on 2026-03-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('query_orchestrator', '0003_multi_domain_ids'),
        ('direct_messaging_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='domain_name',
            field=models.CharField(blank=True, default='', help_text='Domain context for queryless connect requests', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='query_orchestrator.query'),
        ),
    ]
