# Generated by Django 4.2.28 on 2026-02-27 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_id', models.UUIDField()),
                ('content', models.TextField()),
                ('embedding_vector_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('rag_response', models.TextField(blank=True, default='')),
                ('final_response', models.TextField(blank=True, default='')),
                ('follow_up_questions', models.JSONField(default=list)),
                ('matched_seniors', models.JSONField(default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConflictRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_advice', models.TextField()),
                ('conflicting_advice', models.TextField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='query_orchestrator.query')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorQueryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESPONDED', 'Responded'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('advice_content', models.TextField(blank=True, default='')),
                ('answered_followups', models.JSONField(default=list)),
                ('trust_score_at_response', models.FloatField(default=0.0)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='query_orchestrator.query')),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('query', 'senior')},
            },
        ),
    ]
