# Generated by Django 4.2.28 on 2026-03-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_orchestrator', '0002_alter_query_domain_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='domain_id',
        ),
        migrations.AddField(
            model_name='query',
            name='domain_ids',
            field=models.JSONField(default=list, help_text='List of domain ID strings'),
        ),
    ]
