# Generated by Django 4.2.29 on 2026-03-05 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('query_orchestrator', '0004_query_feedback_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('representative_content', models.TextField(help_text='Consolidated question shown to seniors')),
                ('domain_ids', models.JSONField(default=list, help_text='Union of child query domain_ids')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('final_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='query',
            name='is_cluster_lead',
            field=models.BooleanField(default=False, help_text='True for the first query that created the cluster pipeline'),
        ),
        migrations.AddField(
            model_name='query',
            name='cluster',
            field=models.ForeignKey(blank=True, help_text='Cluster this query belongs to (null = standalone)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='query_orchestrator.querycluster'),
        ),
    ]
