# Generated by Django 4.2.29 on 2026-03-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_orchestrator', '0005_query_compaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='finalized_by',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student early finalization'), ('DEADLINE', 'Response window expired'), ('ALL_RESPONDED', 'All assigned seniors responded')], help_text='How the query was finalized (null = not yet finalized)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for senior responses (default: 24h after creation)', null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='response_window_hours',
            field=models.FloatField(default=24.0, help_text='Hours to wait for senior responses before auto-finalize'),
        ),
        migrations.AddField(
            model_name='seniorqueryassignment',
            name='faq_completed',
            field=models.BooleanField(default=False, help_text='True when senior has completed both Step 1 (advice) and Step 2 (FAQs)'),
        ),
    ]
