# Generated by Django 4.2.28 on 2026-02-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustmetrics',
            name='n_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trustmetrics',
            name='n_total',
            field=models.IntegerField(default=0),
        ),
    ]
