# Generated by Django 4.2.28 on 2026-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_trustmetrics_n_success_trustmetrics_n_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
